const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const User = require('./backend/models/User');

dotenv.config();

/**
 * Clean Seed File for Attanzeel Portal Database
 * Creates test users with firstName and lastName fields
 */

// Test Users Data
const testUsers = [
  // Students
  {
    username: 'asi00150',
    password: 'akin150',
    firstName: 'AWWAL',
    lastName: 'AKINWALE',
    email: 'asi00150@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00150',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00151',
    password: 'abdu151',
    firstName: 'MUHAMMAD',
    lastName: 'ABDULAKEEM',
    email: 'asi00151@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00151',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00152',
    password: 'abdu152',
    firstName: 'MUAHZ',
    lastName: 'ABDURROHEEM',
    email: 'asi00152@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00152',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00153',
    password: 'sahe153',
    firstName: 'ABDURROHEEM',
    lastName: 'SAHEED',
    email: 'asi00153@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00153',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00154',
    password: 'abdu154',
    firstName: 'ABDULLAH',
    lastName: 'ABDURROHEEM',
    email: 'asi00154@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00154',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00155',
    password: 'abdu155',
    firstName: 'MUAHZ',
    lastName: 'ABDURROUF',
    email: 'asi00155@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00155',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00156',
    password: 'abdu156',
    firstName: 'ANNAS',
    lastName: 'ABDULKABIR',
    email: 'asi00156@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00156',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00157',
    password: 'osen157',
    firstName: 'ANNAS',
    lastName: 'OSENI',
    email: 'asi00157@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00157',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00158',
    password: 'abdu158',
    firstName: 'ABDULMONNAH',
    lastName: 'ABDURROHEEM',
    email: 'asi00158@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00158',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00159',
    password: 'badm159',
    firstName: 'ABUBAKIR',
    lastName: 'BADMUS',
    email: 'asi00159@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00159',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00160',
    password: 'badm160',
    firstName: 'MUTOLIU',
    lastName: 'BADMUS',
    email: 'asi00160@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00160',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00161',
    password: 'omot161',
    firstName: 'MABUBU',
    lastName: 'OMOTARA',
    email: 'asi00161@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00161',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00162',
    password: 'aden162',
    firstName: 'YUSHRO',
    lastName: 'ADENIYI',
    email: 'asi00162@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00162',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00163',
    password: 'abdu163',
    firstName: 'AISHAT',
    lastName: 'ABDULAKEEM',
    email: 'asi00163@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00163',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00164',
    password: 'abdu164',
    firstName: 'ANEEZAH',
    lastName: 'ABDULAKEEM',
    email: 'asi00164@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00164',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00165',
    password: 'akin165',
    firstName: 'HADEENAH',
    lastName: 'AKINYEMI',
    email: 'asi00165@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00165',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00166',
    password: 'balo166',
    firstName: 'MORIDIYAH',
    lastName: 'BALOGUN',
    email: 'asi00166@attanzeel.edu.ng',
    class: 'Kindergarten 2',
    role: 'student',
    admissionNumber: 'ASI00166',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00167',
    password: 'badm167',
    firstName: 'ABIBAT',
    lastName: 'BADMUS',
    email: 'asi00167@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00167',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00168',
    password: 'muri168',
    firstName: 'HAYATULILLAH',
    lastName: 'MURITADOR',
    email: 'asi00168@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00168',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00169',
    password: 'yusu169',
    firstName: 'MABUBAT',
    lastName: 'YUSUF',
    email: 'asi00169@attanzeel.edu.ng',
    class: 'Kindergarten 1',
    role: 'student',
    admissionNumber: 'ASI00169',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00170',
    password: 'abdu170',
    firstName: 'NUSAIBAH',
    lastName: 'ABDULAKEEM',
    email: 'asi00170@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00170',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00171',
    password: 'akin171',
    firstName: 'MAZEEDAH',
    lastName: 'AKINWALE',
    email: 'asi00171@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00171',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00172',
    password: 'abdu172',
    firstName: 'HAMDALAH',
    lastName: 'ABDULGANIYU',
    email: 'asi00172@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00172',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00173',
    password: 'akin173',
    firstName: 'HAKEEMAH',
    lastName: 'AKINYEMI',
    email: 'asi00173@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00173',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00174',
    password: 'anim174',
    firstName: 'ZAINAB',
    lastName: 'ANIMASHAUN',
    email: 'asi00174@attanzeel.edu.ng',
    class: 'Play Group',
    role: 'student',
    admissionNumber: 'ASI00174',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00175',
    password: 'abdu175',
    firstName: 'ALI',
    lastName: 'ABDULSALAM',
    email: 'asi00175@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00175',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00176',
    password: 'ayan176',
    firstName: 'ABDULSALAM',
    lastName: 'AYANKOJO',
    email: 'asi00176@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00176',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00177',
    password: 'sola177',
    firstName: 'ABDULLAH',
    lastName: 'SOLAJA',
    email: 'asi00177@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00177',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00178',
    password: 'abdu178',
    firstName: 'NAWAL',
    lastName: 'ABDULKABIR',
    email: 'asi00178@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00178',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00179',
    password: 'abdu179',
    firstName: 'RIZKOR',
    lastName: 'ABDULRAHMON',
    email: 'asi00179@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00179',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00180',
    password: 'akin180',
    firstName: 'MUTHMAINAH',
    lastName: 'AKINWALE',
    email: 'asi00180@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00180',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00181',
    password: 'ibra181',
    firstName: 'MARDIYAH',
    lastName: 'IBRAHIM',
    email: 'asi00181@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00181',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00182',
    password: 'lawa182',
    firstName: 'MUTHMAINAH',
    lastName: 'LAWAL',
    email: 'asi00182@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00182',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00183',
    password: 'osen183',
    firstName: 'MAZEEDAH',
    lastName: 'OSENI',
    email: 'asi00183@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00183',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00184',
    password: 'mart184',
    firstName: 'HANIYAH',
    lastName: 'MARTADOR',
    email: 'asi00184@attanzeel.edu.ng',
    class: 'Nursery 1',
    role: 'student',
    admissionNumber: 'ASI00184',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00185',
    password: 'abdu185',
    firstName: 'HANEEF',
    lastName: 'ABDULKABIR',
    email: 'asi00185@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00185',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00186',
    password: 'abdu186',
    firstName: 'IBRAHIM',
    lastName: 'ABDULAKEEM',
    email: 'asi00186@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00186',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00187',
    password: 'abdu187',
    firstName: 'MUJAHEED',
    lastName: 'ABDULWAHEED',
    email: 'asi00187@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00187',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00188',
    password: 'awod188',
    firstName: 'ISMAIL',
    lastName: 'AWODELE',
    email: 'asi00188@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00188',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00189',
    password: 'olar189',
    firstName: 'RAMADAN',
    lastName: 'OLARINOYE',
    email: 'asi00189@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00189',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00190',
    password: 'badm190',
    firstName: 'QONITAH',
    lastName: 'BADMOS',
    email: 'asi00190@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00190',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00191',
    password: 'olab191',
    firstName: 'ALIYAH',
    lastName: 'OLABAMIJI',
    email: 'asi00191@attanzeel.edu.ng',
    class: 'Nursery 2',
    role: 'student',
    admissionNumber: 'ASI00191',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00192',
    password: 'abdu192',
    firstName: 'ABDULLAH',
    lastName: 'ABDULSALAM',
    email: 'asi00192@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00192',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00193',
    password: 'abdu193',
    firstName: 'MAHMUD',
    lastName: 'ABDULROHEEM',
    email: 'asi00193@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00193',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00194',
    password: 'akin194',
    firstName: 'MUQSIT',
    lastName: 'AKINSOLA',
    email: 'asi00194@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00194',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00195',
    password: 'akin195',
    firstName: 'BILAAL',
    lastName: 'AKINWANDE',
    email: 'asi00195@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00195',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00196',
    password: 'badm196',
    firstName: 'FAAIZ',
    lastName: 'BADMUS',
    email: 'asi00196@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00196',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00197',
    password: 'hass197',
    firstName: 'UTHMAN',
    lastName: 'HASSAN',
    email: 'asi00197@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00197',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00198',
    password: 'ibra198',
    firstName: 'MUADH',
    lastName: 'IBRAHIM',
    email: 'asi00198@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00198',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00199',
    password: 'olag199',
    firstName: 'FODHLULLAH',
    lastName: 'OLAGUNJU',
    email: 'asi00199@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00199',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00200',
    password: 'otun200',
    firstName: 'ABDULMALIK',
    lastName: 'OTUNLA',
    email: 'asi00200@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00200',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00201',
    password: 'abdu201',
    firstName: 'NAHEEMOH',
    lastName: 'ABDULLATEEF',
    email: 'asi00201@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00201',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00202',
    password: 'abdu202',
    firstName: 'KHADIJAH',
    lastName: 'ABDULGANIYU',
    email: 'asi00202@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00202',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00203',
    password: 'ibra203',
    firstName: 'AISHAT',
    lastName: 'IBRAHIM',
    email: 'asi00203@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00203',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00204',
    password: 'yaqu204',
    firstName: 'HAMEEDAH',
    lastName: 'YAQUB',
    email: 'asi00204@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00204',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00205',
    password: 'zuba205',
    firstName: 'RODIYAH',
    lastName: 'ZUBAYR',
    email: 'asi00205@attanzeel.edu.ng',
    class: 'Primary 1',
    role: 'student',
    admissionNumber: 'ASI00205',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00206',
    password: 'anim206',
    firstName: 'ABDUL LATEEF',
    lastName: 'ANIMASHAUN',
    email: 'asi00206@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00206',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00207',
    password: 'abdu207',
    firstName: 'ABDUL RAHMAN',
    lastName: 'ABDUL KABIR',
    email: 'asi00207@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00207',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00208',
    password: 'akin208',
    firstName: 'ABDUL SALAM',
    lastName: 'AKINWALE',
    email: 'asi00208@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00208',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00209',
    password: 'bell209',
    firstName: 'ABDUL MUIZ',
    lastName: 'BELLO',
    email: 'asi00209@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00209',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00210',
    password: 'osen210',
    firstName: 'JAMALDEEN',
    lastName: 'OSENI',
    email: 'asi00210@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00210',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00211',
    password: 'akin211',
    firstName: 'FAHEEMAH',
    lastName: 'AKINYEMI',
    email: 'asi00211@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00211',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00212',
    password: 'ibra212',
    firstName: 'ZAINAB',
    lastName: 'IBRAHEEM',
    email: 'asi00212@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00212',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00213',
    password: 'adeb213',
    firstName: 'ROFIAH',
    lastName: 'ADEBAYO',
    email: 'asi00213@attanzeel.edu.ng',
    class: 'Primary 2',
    role: 'student',
    admissionNumber: 'ASI00213',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00214',
    password: 'abdu214',
    firstName: 'FAHIZOL',
    lastName: 'ABDUL GANIY',
    email: 'asi00214@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00214',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00215',
    password: 'adej215',
    firstName: 'UMAR',
    lastName: 'ADEJUMO',
    email: 'asi00215@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00215',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00216',
    password: 'abdu216',
    firstName: 'ABUBAKR',
    lastName: 'ABDUL HAKEEM',
    email: 'asi00216@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00216',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00217',
    password: 'ya\'q217',
    firstName: 'YUUSUF',
    lastName: 'YA\'QUB',
    email: 'asi00217@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00217',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00218',
    password: 'idri218',
    firstName: 'UMAR',
    lastName: 'IDRIS',
    email: 'asi00218@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00218',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00219',
    password: 'omot219',
    firstName: 'ABDUL BAASIT',
    lastName: 'OMOTARA',
    email: 'asi00219@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00219',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00220',
    password: 'abdu220',
    firstName: 'HABEEBAH',
    lastName: 'ABDUL KABEER',
    email: 'asi00220@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00220',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00221',
    password: 'akin221',
    firstName: 'ROFIAH',
    lastName: 'AKINWALE',
    email: 'asi00221@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00221',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00222',
    password: 'akin222',
    firstName: 'MISTUROH',
    lastName: 'AKINWALE',
    email: 'asi00222@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00222',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00223',
    password: 'fadi223',
    firstName: 'KHADIJAH',
    lastName: 'FADIPE',
    email: 'asi00223@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00223',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00224',
    password: 'muri224',
    firstName: 'HADIYYATULLAH',
    lastName: 'MURITADOR',
    email: 'asi00224@attanzeel.edu.ng',
    class: 'Primary 3',
    role: 'student',
    admissionNumber: 'ASI00224',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00225',
    password: 'sahe225',
    firstName: 'NABEEL',
    lastName: 'SAHEED',
    email: 'asi00225@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00225',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00226',
    password: 'zuba226',
    firstName: 'RIDWAN',
    lastName: 'ZUBAYR',
    email: 'asi00226@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00226',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00227',
    password: 'abdu227',
    firstName: 'IMAN',
    lastName: 'ABDUL AKEEM',
    email: 'asi00227@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00227',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00228',
    password: 'adey228',
    firstName: 'KHAIRA',
    lastName: 'ADEYEMO',
    email: 'asi00228@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00228',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00229',
    password: 'ayan229',
    firstName: 'SHUKROH',
    lastName: 'AYANKOJO',
    email: 'asi00229@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00229',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00230',
    password: 'olab230',
    firstName: 'BALIQEES',
    lastName: 'OLABAMIJI',
    email: 'asi00230@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00230',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00231',
    password: 'otun231',
    firstName: 'FARIDAH',
    lastName: 'OTUNLA',
    email: 'asi00231@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00231',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00232',
    password: 'lawa232',
    firstName: 'MARYAM',
    lastName: 'LAWAL',
    email: 'asi00232@attanzeel.edu.ng',
    class: 'Primary 4',
    role: 'student',
    admissionNumber: 'ASI00232',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00233',
    password: 'adel233',
    firstName: 'MUJAHID',
    lastName: 'ADELEKE',
    email: 'asi00233@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00233',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00234',
    password: 'kola234',
    firstName: 'FUAD',
    lastName: 'KOLAWOLE',
    email: 'asi00234@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00234',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00235',
    password: 'sola235',
    firstName: 'ISMAIL',
    lastName: 'SOLAJA',
    email: 'asi00235@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00235',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00236',
    password: 'adul236',
    firstName: 'ZAINAB',
    lastName: 'ADULLATEEF',
    email: 'asi00236@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00236',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00237',
    password: 'abdu237',
    firstName: 'SOLIAH',
    lastName: 'ABDULWAHEED',
    email: 'asi00237@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00237',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00238',
    password: 'alam238',
    firstName: 'SAEEDAH',
    lastName: 'ALAMOLYEKEEN',
    email: 'asi00238@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00238',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00239',
    password: 'akin239',
    firstName: 'MARIAM',
    lastName: 'AKINWALE',
    email: 'asi00239@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00239',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00240',
    password: 'isho240',
    firstName: 'FATIMAH',
    lastName: 'ISHOLA',
    email: 'asi00240@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00240',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00241',
    password: 'john241',
    firstName: 'ROKIBAH',
    lastName: 'JOHN',
    email: 'asi00241@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00241',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00242',
    password: 'muri242',
    firstName: 'AISHAT',
    lastName: 'MURITALA',
    email: 'asi00242@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00242',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00243',
    password: 'osen243',
    firstName: 'SHERIFAH',
    lastName: 'OSENI',
    email: 'asi00243@attanzeel.edu.ng',
    class: 'Primary 5',
    role: 'student',
    admissionNumber: 'ASI00243',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00244',
    password: 'adeg244',
    firstName: 'JUBRIL',
    lastName: 'ADEGOKE',
    email: 'asi00244@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00244',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00245',
    password: 'hass245',
    firstName: 'UMAR',
    lastName: 'HASSAN',
    email: 'asi00245@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00245',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00246',
    password: 'kola246',
    firstName: 'QUDUS',
    lastName: 'KOLAWOLE',
    email: 'asi00246@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00246',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00247',
    password: 'oloy247',
    firstName: 'UMAR',
    lastName: 'OLOYEDE',
    email: 'asi00247@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00247',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00248',
    password: 'omof248',
    firstName: 'MUHAMMAD',
    lastName: 'OMOFOYEWA',
    email: 'asi00248@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00248',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00249',
    password: 'adej249',
    firstName: 'RODIYAH',
    lastName: 'ADEJUMO',
    email: 'asi00249@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00249',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00250',
    password: 'gbol250',
    firstName: 'FATHIA',
    lastName: 'GBOLAGADE',
    email: 'asi00250@attanzeel.edu.ng',
    class: 'JSS 1',
    role: 'student',
    admissionNumber: 'ASI00250',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00251',
    password: 'abdu251',
    firstName: 'HAMMOD',
    lastName: 'ABDUL KABEER',
    email: 'asi00251@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00251',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00252',
    password: 'abdu252',
    firstName: 'MUHAMMED',
    lastName: 'ABDULWASII',
    email: 'asi00252@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00252',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00253',
    password: 'adel253',
    firstName: 'MUJEEB',
    lastName: 'ADELEKE',
    email: 'asi00253@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00253',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00254',
    password: 'afol254',
    firstName: 'MUHAMMED',
    lastName: 'AFOLARIN',
    email: 'asi00254@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00254',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00255',
    password: 'ahme255',
    firstName: 'IDRIS',
    lastName: 'AHMED',
    email: 'asi00255@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00255',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00256',
    password: 'lawa256',
    firstName: 'ABDULQOYUM',
    lastName: 'LAWAL',
    email: 'asi00256@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00256',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00257',
    password: 'olay257',
    firstName: 'SULAIMON',
    lastName: 'OLAYIWOLA',
    email: 'asi00257@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00257',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00258',
    password: 'abdu258',
    firstName: 'HADDIYYAH',
    lastName: 'ABDULRAZAK',
    email: 'asi00258@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00258',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00259',
    password: 'abdu259',
    firstName: 'FATIMAH',
    lastName: 'ABDULROFIU',
    email: 'asi00259@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00259',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00260',
    password: 'aden260',
    firstName: 'HALEEMAH',
    lastName: 'ADENIRAN',
    email: 'asi00260@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00260',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00261',
    password: 'akin261',
    firstName: 'SEKEENAH',
    lastName: 'AKINSOLA',
    email: 'asi00261@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00261',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00262',
    password: 'olag262',
    firstName: 'FAREEDAH',
    lastName: 'OLAGUNJU',
    email: 'asi00262@attanzeel.edu.ng',
    class: 'JSS 2',
    role: 'student',
    admissionNumber: 'ASI00262',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00263',
    password: 'adey263',
    firstName: 'ABDULLAHI',
    lastName: 'ADEYEMI',
    email: 'asi00263@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00263',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00264',
    password: 'ayan264',
    firstName: 'IDRIS',
    lastName: 'AYANKOJO',
    email: 'asi00264@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00264',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00265',
    password: 'ibra265',
    firstName: 'FAWAS',
    lastName: 'IBRAHIM',
    email: 'asi00265@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00265',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00266',
    password: 'ibra266',
    firstName: 'SULAIMON',
    lastName: 'IBRAHIM',
    email: 'asi00266@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00266',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00267',
    password: 'olab267',
    firstName: 'ABDULBAASIT',
    lastName: 'OLABAMIJI',
    email: 'asi00267@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00267',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00268',
    password: 'sahe268',
    firstName: 'ABDULSALAM',
    lastName: 'SAHEED',
    email: 'asi00268@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00268',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00269',
    password: 'adek269',
    firstName: 'SOFIYAH',
    lastName: 'ADEKUNLE',
    email: 'asi00269@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00269',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00270',
    password: 'ibra270',
    firstName: 'FIRDAOS',
    lastName: 'IBRAHIM',
    email: 'asi00270@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00270',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00271',
    password: 'tawh271',
    firstName: 'NABEELAH',
    lastName: 'TAWHEED',
    email: 'asi00271@attanzeel.edu.ng',
    class: 'JSS 3',
    role: 'student',
    admissionNumber: 'ASI00271',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00272',
    password: 'abdu272',
    firstName: 'IBRAHIM',
    lastName: 'ABDULROFIU',
    email: 'asi00272@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00272',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00273',
    password: 'adeg273',
    firstName: 'MUSTAPHA',
    lastName: 'ADEGUNJU',
    email: 'asi00273@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00273',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00274',
    password: 'akin274',
    firstName: 'ANAS',
    lastName: 'AKINSOLA',
    email: 'asi00274@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00274',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00275',
    password: 'otun275',
    firstName: 'TAOHEED',
    lastName: 'OTUNLA',
    email: 'asi00275@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00275',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00276',
    password: 'sola276',
    firstName: 'ABDULMALIK',
    lastName: 'SOLADOYE',
    email: 'asi00276@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00276',
    department: 'Commercial',
    isActive: true,
  },
  {
    username: 'asi00277',
    password: 'abdu277',
    firstName: 'ROBIAH',
    lastName: 'ABDULGANIY',
    email: 'asi00277@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00277',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00278',
    password: 'adey278',
    firstName: 'KAREEMAH',
    lastName: 'ADEYEMO',
    email: 'asi00278@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00278',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00279',
    password: 'lawa279',
    firstName: 'QOWIYAH',
    lastName: 'LAWAL',
    email: 'asi00279@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00279',
    department: 'Art',
    isActive: true,
  },
  {
    username: 'asi00280',
    password: 'sahe280',
    firstName: 'NABEELAH',
    lastName: 'SAHEED',
    email: 'asi00280@attanzeel.edu.ng',
    class: 'SS 1',
    role: 'student',
    admissionNumber: 'ASI00280',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00281',
    password: 'abdu281',
    firstName: 'ABDULWAARITH',
    lastName: 'ABDULWASII',
    email: 'asi00281@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00281',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00282',
    password: 'bell282',
    firstName: 'ABDUL MUIZ',
    lastName: 'BELLO',
    email: 'asi00282@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00282',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00283',
    password: 'hass283',
    firstName: 'ABDUL AZEEZ',
    lastName: 'HASSAN',
    email: 'asi00283@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00283',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00284',
    password: 'lawa284',
    firstName: 'SIDEEQ',
    lastName: 'LAWAL',
    email: 'asi00284@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00284',
    department: 'Art',
    isActive: true,
  },
  {
    username: 'asi00285',
    password: 'maka285',
    firstName: 'AYYUB',
    lastName: 'MAKANJUOLA',
    email: 'asi00285@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00285',
    department: '',
    isActive: true,
  },
  {
    username: 'asi00286',
    password: 'olal286',
    firstName: 'ABDUL LATEEF',
    lastName: 'OLALERE',
    email: 'asi00286@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00286',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00287',
    password: 'abdu287',
    firstName: 'FAATIMAH',
    lastName: 'ABDULKABIR',
    email: 'asi00287@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00287',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00288',
    password: 'ayan288',
    firstName: 'AISHA',
    lastName: 'AYANKOJO',
    email: 'asi00288@attanzeel.edu.ng',
    class: 'SS 2',
    role: 'student',
    admissionNumber: 'ASI00288',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00289',
    password: 'abdu289',
    firstName: 'ABDUL RAHMAN',
    lastName: 'ABDUL RAZAQ',
    email: 'asi00289@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00289',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00290',
    password: 'adek290',
    firstName: 'RASHEED',
    lastName: 'ADEKUNLE',
    email: 'asi00290@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00290',
    department: 'Science',
    isActive: true,
  },
  {
    username: 'asi00291',
    password: 'akin291',
    firstName: 'ABDUL AZEEZ',
    lastName: 'AKINWALE',
    email: 'asi00291@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00291',
    department: 'Art',
    isActive: true,
  },
  {
    username: 'asi00292',
    password: 'otun292',
    firstName: 'FAWAZ',
    lastName: 'OTUNLA',
    email: 'asi00292@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00292',
    department: 'Art',
    isActive: true,
  },
  {
    username: 'asi00293',
    password: 'safi293',
    firstName: 'YUSUFF',
    lastName: 'SAFIYULLAH',
    email: 'asi00293@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00293',
    department: 'Art',
    isActive: true,
  },
  {
    username: 'asi00294',
    password: 'aded294',
    firstName: 'MUTHMAINAH',
    lastName: 'ADEDIGBA',
    email: 'asi00294@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00294',
    department: 'Commercial',
    isActive: true,
  },
  {
    username: 'asi00295',
    password: 'akin295',
    firstName: 'ALIYAH',
    lastName: 'AKINDAPO',
    email: 'asi00295@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00295',
    department: 'Commercial',
    isActive: true,
  },
  {
    username: 'asi00296',
    password: 'muri296',
    firstName: 'FATHIA',
    lastName: 'MURITALA',
    email: 'asi00296@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00296',
    department: 'Commercial',
    isActive: true,
  },
  {
    username: 'asi00297',
    password: 'sira297',
    firstName: 'ROQEEBAH',
    lastName: 'SIRAJUDEEN',
    email: 'asi00297@attanzeel.edu.ng',
    class: 'SS 3',
    role: 'student',
    admissionNumber: 'ASI00297',
    department: 'Commercial',
    isActive: true,
  },
  // Staff
  {
    username: 'staff_001',
    password: 'staff123',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@attanzeel.edu.ng',
    role: 'staff',
    department: 'Mathematics',
    isActive: true,
  },
  {
    username: 'staff_002',
    password: 'staff123',
    firstName: 'Adekunle',
    lastName: 'Afolabi',
    email: 'adekunle@attanzeel.edu.ng',
    role: 'staff',
    department: 'English Language',
    isActive: true,
  },
  {
    username: 'staff_003',
    password: 'staff123',
    firstName: 'Zainab',
    lastName: 'Muhammad',
    email: 'zainab@attanzeel.edu.ng',
    role: 'staff',
    department: 'Science',
    isActive: true,
  },
  // Admin
  {
    username: 'admin_001',
    password: 'admin123',
    firstName: 'System',
    lastName: 'Administrator',
    email: 'admin@attanzeel.edu.ng',
    role: 'admin',
    isActive: true,
  },
];

/**
 * Seed the database with test users
 */
async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✓ Connected to MongoDB\n');

    // Clear existing users
    const deletedCount = await User.deleteMany({});
    console.log(`✓ Cleared ${deletedCount.deletedCount} existing users`);

    // Hash all passwords before creation
    console.log('✓ Hashing passwords...');
    const hashedUsers = await Promise.all(
      testUsers.map(async (userData) => {
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(userData.password, salt);
        return {
          ...userData,
          password: hashedPassword,
        };
      })
    );

    // Create users with already hashed passwords
    const createdUsers = await User.insertMany(hashedUsers);
    console.log(`✓ Created ${createdUsers.length} new users\n`);

    // Display created users
    displayUsers(createdUsers);

    console.log('═════════════════════════════════════════════════════════════════');
    console.log('✓ Database seeding completed successfully!');
    console.log('✓ You can now login to the portal with these credentials.\n');

    process.exit(0);
  } catch (error) {
    console.error('✗ Error seeding database:', error.message);
    process.exit(1);
  }
}

/**
 * Display seeded users in formatted output
 */
function displayUsers(users) {
  console.log('📋 Seeded Users:');
  console.log('═════════════════════════════════════════════════════════════════\n');

  const students = users.filter(u => u.role === 'student');
  const staff = users.filter(u => u.role === 'staff');
  const admins = users.filter(u => u.role === 'admin');

  // Display Students
  console.log('🎓 STUDENTS (Password: student123)');
  students.forEach(user => {
    console.log(`  • Username: ${user.username}`);
    console.log(`    Name: ${user.firstName} ${user.lastName}`);
    console.log(`    Email: ${user.email}`);
    console.log(`    Admission #: ${user.admissionNumber}\n`);
  });

  // Display Staff
  console.log('👨‍🏫 STAFF (Password: staff123)');
  staff.forEach(user => {
    console.log(`  • Username: ${user.username}`);
    console.log(`    Name: ${user.firstName} ${user.lastName}`);
    console.log(`    Email: ${user.email}`);
    console.log(`    Department: ${user.department}\n`);
  });

  // Display Admin
  console.log('🔐 ADMIN (Password: admin123)');
  admins.forEach(user => {
    console.log(`  • Username: ${user.username}`);
    console.log(`    Name: ${user.firstName} ${user.lastName}`);
    console.log(`    Email: ${user.email}\n`);
  });
}

// Run seed function
seedDatabase();
